/**
 * mockVeiculos.js
 * Localização: src/utils/mockVeiculos.js
 * 
 * Lista de 25 viaturas realistas para teste do catálogo TVDE em Portugal.
 * Inclui dados de autonomia (para elétricos), lotação (para XL), tarifas e imagens demonstrativas.
 */

export const MOCK_VEICULOS = [
  {
    id: "v-tesla-m3-01",
    marca: "Tesla",
    modelo: "Model 3 Standard Range",
    ano: 2023,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-88-XX",
    cor: "Branco Pérola",
    lugares: 5,
    autonomia: 491, // km
    categoria: "Green / Comfort",
    precoSemana: 250, // €/semana comum para aluguer TVDE
    caucao: 400,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&q=80&w=600",
    destaque: true
  },
  {
    id: "v-dacia-jog-02",
    marca: "Dacia",
    modelo: "Jogger Comfort Stepway",
    ano: 2024,
    combustivel: "GPL / Gasolina",
    transmissao: "Manual",
    matricula: "AA-12-YY",
    cor: "Cinzento Cometa",
    lugares: 7,
    autonomia: 1000, // Bi-fuel
    categoria: "Standard / XL",
    precoSemana: 220,
    caucao: 350,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=600", // Representativo
    destaque: true
  },
  {
    id: "v-toyota-cor-03",
    marca: "Toyota",
    modelo: "Corolla Touring Sports",
    ano: 2022,
    combustivel: "Híbrido (Gasolina)",
    transmissao: "Automática",
    matricula: "99-ZZ-44",
    cor: "Preto Metálico",
    lugares: 5,
    autonomia: 850,
    categoria: "Standard / Comfort",
    precoSemana: 210,
    caucao: 300,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1621007947382-cc34aa8668c2?auto=format&fit=crop&q=80&w=600",
    destaque: true
  },
  {
    id: "v-renault-zoe-04",
    marca: "Renault",
    modelo: "Zoe E-Tech GT Line",
    ano: 2022,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-55-ZZ",
    cor: "Azul Céleste",
    lugares: 5,
    autonomia: 385,
    categoria: "Green",
    precoSemana: 190,
    caucao: 300,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1554744512-d6c603f27c54?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-peugeot-2008-05",
    marca: "Peugeot",
    modelo: "e-2008 GT",
    ano: 2023,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-99-AA",
    cor: "Cinzento Platinium",
    lugares: 5,
    autonomia: 345,
    categoria: "Green / Standard",
    precoSemana: 230,
    caucao: 400,
    estado: "Alugado",
    imagem: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-nissan-leaf-06",
    marca: "Nissan",
    modelo: "Leaf Acenta II",
    ano: 2021,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "35-XD-82",
    cor: "Branco",
    lugares: 5,
    autonomia: 270,
    categoria: "Green / Standard",
    precoSemana: 180,
    caucao: 300,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1536700503339-1e4b06520771?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-kia-niro-07",
    marca: "Kia",
    modelo: "Niro EV Concept",
    ano: 2023,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-33-CC",
    cor: "Preto",
    lugares: 5,
    autonomia: 460,
    categoria: "Green / Comfort",
    precoSemana: 240,
    caucao: 400,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1678767931327-05c04e223508?auto=format&fit=crop&q=80&w=600",
    destaque: true
  },
  {
    id: "v-hyundai-io5-08",
    marca: "Hyundai",
    modelo: "Ioniq 5 Premium",
    ano: 2023,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-44-DD",
    cor: "Cinzento Matte",
    lugares: 5,
    autonomia: 507,
    categoria: "Green / Comfort / Black",
    precoSemana: 280,
    caucao: 500,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1669045751911-09689877b066?auto=format&fit=crop&q=80&w=600",
    destaque: true
  },
  {
    id: "v-mbenz-eqe-09",
    marca: "Mercedes-Benz",
    modelo: "EQE 350+",
    ano: 2024,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-22-EE",
    cor: "Preto Obsidiana",
    lugares: 5,
    autonomia: 639,
    categoria: "Black",
    precoSemana: 390,
    caucao: 750,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=600",
    destaque: true
  },
  {
    id: "v-tesla-my-10",
    marca: "Tesla",
    modelo: "Model Y Long Range",
    ano: 2024,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-11-FF",
    cor: "Cinzento Midnight",
    lugares: 5,
    autonomia: 533,
    categoria: "Green / Comfort",
    precoSemana: 275,
    caucao: 500,
    estado: "Alugado",
    imagem: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-citroen-ec4-11",
    marca: "Citroën",
    modelo: "ë-C4 Feel Pack",
    ano: 2022,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-77-GG",
    cor: "Cinzento Platinum",
    lugares: 5,
    autonomia: 350,
    categoria: "Green / Standard",
    precoSemana: 205,
    caucao: 350,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-skoda-oct-12",
    marca: "Skoda",
    modelo: "Octavia Break IV Hybrid",
    ano: 2022,
    combustivel: "Híbrido Plug-In",
    transmissao: "Automática",
    matricula: "42-ZR-10",
    cor: "Azul Lava",
    lugares: 5,
    autonomia: 800, // Total
    categoria: "Standard / Comfort",
    precoSemana: 215,
    caucao: 300,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-peugeot-5008-13",
    marca: "Peugeot",
    modelo: "5008 BlueHDi S&S",
    ano: 2021,
    combustivel: "Diesel",
    transmissao: "Automática",
    matricula: "11-YV-99",
    cor: "Preto Perla Nera",
    lugares: 7,
    autonomia: 950,
    categoria: "Standard / XL",
    precoSemana: 245,
    caucao: 400,
    estado: "Manutenção",
    imagem: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-renault-clio-14",
    marca: "Renault",
    modelo: "Clio V Sport Tourer LPG",
    ano: 2021,
    combustivel: "GPL / Gasolina",
    transmissao: "Manual",
    matricula: "88-UT-12",
    cor: "Cinzento Urban",
    lugares: 5,
    autonomia: 900,
    categoria: "Standard",
    precoSemana: 175,
    caucao: 250,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-mg4-15",
    marca: "MG",
    modelo: "4 Electric Luxury",
    ano: 2023,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-99-BB",
    cor: "Laranja Fizzy",
    lugares: 5,
    autonomia: 435,
    categoria: "Green / Standard",
    precoSemana: 210,
    caucao: 350,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-seat-leon-16",
    marca: "SEAT",
    modelo: "Leon Sportstourer e-Hybrid",
    ano: 2022,
    combustivel: "Híbrido Plug-In",
    transmissao: "Automática",
    matricula: "55-ZX-33",
    cor: "Branco Nevada",
    lugares: 5,
    autonomia: 780,
    categoria: "Standard / Comfort",
    precoSemana: 200,
    caucao: 300,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-volkswagen-id4-17",
    marca: "Volkswagen",
    modelo: "ID.4 Pro Performance",
    ano: 2023,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-11-HH",
    cor: "Azul Dusk",
    lugares: 5,
    autonomia: 522,
    categoria: "Green / Comfort",
    precoSemana: 260,
    caucao: 450,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1525609004556-c46c7d6cf0a3?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-opel-mokka-18",
    marca: "Opel",
    modelo: "Mokka-e Ultimate",
    ano: 2022,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-22-JJ",
    cor: "Verde Matcha",
    lugares: 5,
    autonomia: 338,
    categoria: "Green / Standard",
    precoSemana: 195,
    caucao: 300,
    estado: "Alugado",
    imagem: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-volvo-xc40-19",
    marca: "Volvo",
    modelo: "XC40 Recharge Single Motor",
    ano: 2023,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-55-KK",
    cor: "Azul Fjord",
    lugares: 5,
    autonomia: 425,
    categoria: "Green / Comfort",
    precoSemana: 270,
    caucao: 500,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-ford-focus-20",
    marca: "Ford",
    modelo: "Focus SW EcoBoost Hybrid",
    ano: 2021,
    combustivel: "Híbrido (Gasolina)",
    transmissao: "Manual",
    matricula: "67-YP-45",
    cor: "Cinzento Magnetic",
    lugares: 5,
    autonomia: 850,
    categoria: "Standard",
    precoSemana: 185,
    caucao: 300,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-bmw-i4-21",
    marca: "BMW",
    modelo: "i4 eDrive35 Gran Coupé",
    ano: 2023,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-66-LL",
    cor: "Preto Safira",
    lugares: 5,
    autonomia: 483,
    categoria: "Black",
    precoSemana: 340,
    caucao: 600,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=600",
    destaque: true
  },
  {
    id: "v-dacia-log-22",
    marca: "Dacia",
    modelo: "Logan Comfort TCe ECO-G",
    ano: 2022,
    combustivel: "GPL / Gasolina",
    transmissao: "Manual",
    matricula: "10-ZX-89",
    cor: "Branco Glaciar",
    lugares: 5,
    autonomia: 1000,
    categoria: "Standard",
    precoSemana: 170,
    caucao: 250,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-mbenz-c220-23",
    marca: "Mercedes-Benz",
    modelo: "C 220 d Limousine",
    ano: 2022,
    combustivel: "Diesel / Híbrido MHEV",
    transmissao: "Automática",
    matricula: "33-ZV-22",
    cor: "Cinzento Selenite",
    lugares: 5,
    autonomia: 1050,
    categoria: "Comfort / Black",
    precoSemana: 300,
    caucao: 500,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-fiat-tipo-24",
    marca: "Fiat",
    modelo: "Tipo SW Life MultiJet",
    ano: 2021,
    combustivel: "Diesel",
    transmissao: "Manual",
    matricula: "91-YA-88",
    cor: "Azul Venezia",
    lugares: 5,
    autonomia: 900,
    categoria: "Standard",
    precoSemana: 180,
    caucao: 300,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=600",
    destaque: false
  },
  {
    id: "v-audi-q4-25",
    marca: "Audi",
    modelo: "Q4 e-tron 40",
    ano: 2023,
    combustivel: "Elétrico",
    transmissao: "Automática",
    matricula: "AA-99-MM",
    cor: "Cinzento Pebble",
    lugares: 5,
    autonomia: 520,
    categoria: "Green / Comfort",
    precoSemana: 290,
    caucao: 500,
    estado: "Disponível",
    imagem: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=600",
    destaque: false
  }
];